server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://softsquarddb.c9uh8w1pl8iw.ap-northeast-2.rds.amazonaws.com:3306/netflixDB?autoReconnect=true # 변경해주세요
    username: hankyul # 변경해주세요
    password: ksol0820* # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전